// <auto-generated />
using System;
using DW_26256_27229.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DW_26256_27229.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715160229_AjusteChaveCompostaMN")]
    partial class AjusteChaveCompostaMN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DW_26256_27229.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Workshop Técnico"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Palestra"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Torneio de Gaming"
                        });
                });

            modelBuilder.Entity("DW_26256_27229.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VagasMaximas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataHora = new DateTime(2026, 10, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Introdução a Redes Cisco e Routing",
                            UtilizadorId = 1,
                            VagasMaximas = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 3,
                            DataHora = new DateTime(2026, 11, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Torneio Local Co-op (Rayman Legends)",
                            UtilizadorId = 1,
                            VagasMaximas = 16
                        });
                });

            modelBuilder.Entity("DW_26256_27229.Models.Inscricao", b =>
                {
                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("TEXT");

                    b.HasKey("EventoId", "UtilizadorId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("DW_26256_27229.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUtilizador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@ipt.pt",
                            Nome = "Administrador Principal",
                            Password = "123",
                            TipoUtilizador = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "aluno@ipt.pt",
                            Nome = "Aluno Teste",
                            Password = "123",
                            TipoUtilizador = "Aluno"
                        },
                        new
                        {
                            Id = 3,
                            Email = "professor@ipt.pt",
                            Nome = "Professor Teste",
                            Password = "123",
                            TipoUtilizador = "Professor"
                        });
                });

            modelBuilder.Entity("DW_26256_27229.Models.Evento", b =>
                {
                    b.HasOne("DW_26256_27229.Models.Categoria", "Categoria")
                        .WithMany("Eventos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DW_26256_27229.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("DW_26256_27229.Models.Inscricao", b =>
                {
                    b.HasOne("DW_26256_27229.Models.Evento", "Evento")
                        .WithMany("Inscricoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DW_26256_27229.Models.Utilizador", "Utilizador")
                        .WithMany("Inscricoes")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("DW_26256_27229.Models.Categoria", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("DW_26256_27229.Models.Evento", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("DW_26256_27229.Models.Utilizador", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
